Refactor/base fragment[ARC-1848]
andguladzeshio/Netflex pull request #6
Opened 2021-11-01 10:06 UTC by andguladzeshio

https://spaceneobank.atlassian.net/browse/ARC-1848

2021-11-01 10:21 UTC, giorgiqemoklidze approved these changes

2021-11-01 12:30 UTC, AnaRusadze requested changes

2021-11-01 12:30 UTC, AnaRusadze commented on app/src/main/java/com/example/netflex/fragment/base/BaseFragment.kt
> +    abstract fun initView(binding: VB)
ინიტვიუს ფუნქცია ზედმეტია, ამ შემთხვევაში მის ფუნქციასაც onBindViewModel ასრულებს

2021-11-01 12:30 UTC, AnaRusadze commented on app/src/main/java/com/example/netflex/fragment/SplashScreenFragment.kt
> +            binding.appName?.executeAnimation(requireContext(), R.anim.splash_to_collection_anim_name, ANIMATION_DURATION)
with(binding) გამოიყენე

2021-11-01 12:30 UTC, AnaRusadze commented on app/src/main/java/com/example/netflex/fragment/base/BaseFragment.kt
> +    abstract val viewModel: VM
ჯობია ცვლადები ზევით აიტანო

2021-11-01 12:32 UTC, AnaRusadze requested changes

2021-11-01 12:32 UTC, AnaRusadze commented on app/src/main/java/com/example/netflex/fragment/base/BaseFragment.kt
> +        onBindViewModel(viewmodel)
onBindViewModel(viewmodel) onViewCreatedში გამოიძახე

2021-11-01 13:08 UTC, andguladzeshio commented on app/src/main/java/com/example/netflex/fragment/base/BaseFragment.kt
> +    abstract fun initView(binding: VB)
done

2021-11-01 13:10 UTC, andguladzeshio commented on app/src/main/java/com/example/netflex/fragment/base/BaseFragment.kt
> +    abstract fun inflate(layoutInflater: LayoutInflater, viewGroup: ViewGroup?, attachToRoot: Boolean): VB
თვითონ ესაა ონქრიეითვიუში გამოძახებული ინფლეიტი რომელიც იფარება ფრაგმენტებში რომ სწორი ბაინდინგი დაგვიბრუნოს

2021-11-01 13:10 UTC, andguladzeshio commented on app/src/main/java/com/example/netflex/fragment/SplashScreenFragment.kt
> +            binding.appName?.executeAnimation(requireContext(), R.anim.splash_to_collection_anim_name, ANIMATION_DURATION)
done

2021-11-01 13:10 UTC, andguladzeshio commented on app/src/main/java/com/example/netflex/fragment/base/BaseFragment.kt
> +        onBindViewModel(viewmodel)
done

2021-11-01 13:36 UTC, andguladzeshio commented on app/src/main/java/com/example/netflex/fragment/base/BaseFragment.kt
> +    abstract fun inflate(layoutInflater: LayoutInflater, viewGroup: ViewGroup?, attachToRoot: Boolean): VB
ცვლადად გადავეცი ეს ინფლეიტი და მგონი უკეთესია მთლიანი ფუნქციის წერა აღარაა საჭირო

2021-11-02 08:04 UTC, GiorgiMamagulashvili16 approved these changes

2021-11-02 10:48 UTC, AnaRusadze requested changes

2021-11-02 10:48 UTC, AnaRusadze commented on app/src/main/java/com/example/netflex/fragment/MovieCollectionFragment.kt
> +        get() = FragmentMovieCollectionBinding::inflate
შიო, სამიდან არცერთი პარამეტრის ცოდნა არ სჭირდება შვილ ფრაგმენტს, ზედმეტია ყველა. 
https://stackoverflow.com/questions/64819181/how-to-make-basefragment-with-view-binding

2021-11-02 10:50 UTC, AnaRusadze requested changes

2021-11-02 10:50 UTC, AnaRusadze commented on app/src/main/java/com/example/netflex/fragment/base/BaseFragment.kt
> +    private lateinit var viewmodel: VM
არ გჭირდება ეს ცვლადი, protected abstract var გახადე viewModel და ეგ გამოიყენე ყველგან

2021-11-03 07:30 UTC, andguladzeshio commented on app/src/main/java/com/example/netflex/fragment/base/BaseFragment.kt
> +    private lateinit var viewmodel: VM
done

2021-11-03 07:33 UTC, andguladzeshio commented on app/src/main/java/com/example/netflex/fragment/MovieCollectionFragment.kt
> +        get() = FragmentMovieCollectionBinding::inflate
ისე ეს პარამეტრებიც არაა უბრალოდ ტიპია დაკონკრეტებული ცვლადის იმიტორო ინფლეიტის ფუნქცია თვითონ ოვერლოუდ ფუნქციაა და რო გაიგოს რომელი გამოიყენოს

2021-11-03 08:37 UTC, merged